kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 20
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: 10.26.35.245:8082/hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: regsecret
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      #nodePort: 30081
  selector:
    app: hello-world
