kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: bpms
  name: bpms
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 20
  selector:
    matchLabels:
      app: bpms
  template:
    metadata:
      labels:
        app: bpms
    spec:
      containers:
      - name: bpms
        image: 10.26.35.245:8082/bpms:v2.0
        #imagePullPolicy: Always 
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: regsecret
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: bpms
  name: bpms
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
#      nodePort: 32000 
  selector:
    app: bpms
