kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: testdemo3
  name: testdemo3
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

  selector:
    matchLabels:
      app: testdemo3
  template:
    metadata:
      labels:
        app: testdemo3
    spec:
      containers:
      - name: testdemo3
        image: 10.26.35.245:8082/testdemo3:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: nexusseckey
        readinessProbe:
          httpGet:
             path: /
             port: 8080
             initialDelaySeconds: 3
             periodSeconds: 3
             successThreshold: 1
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: testdemo3
  name: testdemo3
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
     # nodePort: 32000
  selector:
    app: testdemo3
