- hosts: Dev
  vars:
   var1: '/rfabdemo-ms/testserv1853'
   var2: 'testserv1853'
 
  tasks:
    - name: Set first line at EOF (1/3)
      lineinfile: dest=/home/ubuntu/append/demo.txt regexp="^string 1" line="string 4"
    - name: Set second line after first (2/3)
      lineinfile: dest=/home/ubuntu/append/demo.txt regexp="^string 2" line="string 2" insertafter="^string 1"
    - name: Set third line after second (3/3)
      lineinfile: dest=/home/ubuntu/append/demo.txt regexp="^string 3" line="string 3" insertafter="^string 2"
